wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726090326
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.5
      5: 0.17.5
      8:
      - 4
      - 5
      13: darwin-arm64
