wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/classify_rsmProp.py
    python_version: 3.11.5
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727390702
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.11.5
      5: 0.17.5
      8:
      - 4
      - 5
      13: darwin-arm64
